// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1"
	scheme "github.com/kubeflow/pytorch-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AmlPyTorchJobsGetter has a method to return a AmlPyTorchJobInterface.
// A group's client should implement this interface.
type AmlPyTorchJobsGetter interface {
	AmlPyTorchJobs(namespace string) AmlPyTorchJobInterface
}

// AmlPyTorchJobInterface has methods to work with AmlPyTorchJob resources.
type AmlPyTorchJobInterface interface {
	Create(*v1.AmlPyTorchJob) (*v1.AmlPyTorchJob, error)
	Update(*v1.AmlPyTorchJob) (*v1.AmlPyTorchJob, error)
	UpdateStatus(*v1.AmlPyTorchJob) (*v1.AmlPyTorchJob, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AmlPyTorchJob, error)
	List(opts metav1.ListOptions) (*v1.AmlPyTorchJobList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AmlPyTorchJob, err error)
	AmlPyTorchJobExpansion
}

// amlPyTorchJobs implements AmlPyTorchJobInterface
type amlPyTorchJobs struct {
	client rest.Interface
	ns     string
}

// newAmlPyTorchJobs returns a AmlPyTorchJobs
func newAmlPyTorchJobs(c *AzuremlV1Client, namespace string) *amlPyTorchJobs {
	return &amlPyTorchJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the amlPyTorchJob, and returns the corresponding amlPyTorchJob object, and an error if there is any.
func (c *amlPyTorchJobs) Get(name string, options metav1.GetOptions) (result *v1.AmlPyTorchJob, err error) {
	result = &v1.AmlPyTorchJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AmlPyTorchJobs that match those selectors.
func (c *amlPyTorchJobs) List(opts metav1.ListOptions) (result *v1.AmlPyTorchJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AmlPyTorchJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested amlPyTorchJobs.
func (c *amlPyTorchJobs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a amlPyTorchJob and creates it.  Returns the server's representation of the amlPyTorchJob, and an error, if there is any.
func (c *amlPyTorchJobs) Create(amlPyTorchJob *v1.AmlPyTorchJob) (result *v1.AmlPyTorchJob, err error) {
	result = &v1.AmlPyTorchJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		Body(amlPyTorchJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a amlPyTorchJob and updates it. Returns the server's representation of the amlPyTorchJob, and an error, if there is any.
func (c *amlPyTorchJobs) Update(amlPyTorchJob *v1.AmlPyTorchJob) (result *v1.AmlPyTorchJob, err error) {
	result = &v1.AmlPyTorchJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		Name(amlPyTorchJob.Name).
		Body(amlPyTorchJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *amlPyTorchJobs) UpdateStatus(amlPyTorchJob *v1.AmlPyTorchJob) (result *v1.AmlPyTorchJob, err error) {
	result = &v1.AmlPyTorchJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		Name(amlPyTorchJob.Name).
		SubResource("status").
		Body(amlPyTorchJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the amlPyTorchJob and deletes it. Returns an error if one occurs.
func (c *amlPyTorchJobs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *amlPyTorchJobs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched amlPyTorchJob.
func (c *amlPyTorchJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AmlPyTorchJob, err error) {
	result = &v1.AmlPyTorchJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("amlpytorchjobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
