// Copyright 2020 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	pytorchv1 "github.com/kubeflow/pytorch-operator/pkg/apis/pytorch/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAmlPyTorchJobs implements AmlPyTorchJobInterface
type FakeAmlPyTorchJobs struct {
	Fake *FakeAzuremlV1
	ns   string
}

var amlpytorchjobsResource = schema.GroupVersionResource{Group: "azureml.microsoft.com", Version: "v1", Resource: "amlpytorchjobs"}

var amlpytorchjobsKind = schema.GroupVersionKind{Group: "azureml.microsoft.com", Version: "v1", Kind: "AmlPyTorchJob"}

// Get takes name of the amlPyTorchJob, and returns the corresponding amlPyTorchJob object, and an error if there is any.
func (c *FakeAmlPyTorchJobs) Get(name string, options v1.GetOptions) (result *pytorchv1.AmlPyTorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(amlpytorchjobsResource, c.ns, name), &pytorchv1.AmlPyTorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pytorchv1.AmlPyTorchJob), err
}

// List takes label and field selectors, and returns the list of AmlPyTorchJobs that match those selectors.
func (c *FakeAmlPyTorchJobs) List(opts v1.ListOptions) (result *pytorchv1.AmlPyTorchJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(amlpytorchjobsResource, amlpytorchjobsKind, c.ns, opts), &pytorchv1.AmlPyTorchJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &pytorchv1.AmlPyTorchJobList{ListMeta: obj.(*pytorchv1.AmlPyTorchJobList).ListMeta}
	for _, item := range obj.(*pytorchv1.AmlPyTorchJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested amlPyTorchJobs.
func (c *FakeAmlPyTorchJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(amlpytorchjobsResource, c.ns, opts))

}

// Create takes the representation of a amlPyTorchJob and creates it.  Returns the server's representation of the amlPyTorchJob, and an error, if there is any.
func (c *FakeAmlPyTorchJobs) Create(amlPyTorchJob *pytorchv1.AmlPyTorchJob) (result *pytorchv1.AmlPyTorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(amlpytorchjobsResource, c.ns, amlPyTorchJob), &pytorchv1.AmlPyTorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pytorchv1.AmlPyTorchJob), err
}

// Update takes the representation of a amlPyTorchJob and updates it. Returns the server's representation of the amlPyTorchJob, and an error, if there is any.
func (c *FakeAmlPyTorchJobs) Update(amlPyTorchJob *pytorchv1.AmlPyTorchJob) (result *pytorchv1.AmlPyTorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(amlpytorchjobsResource, c.ns, amlPyTorchJob), &pytorchv1.AmlPyTorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pytorchv1.AmlPyTorchJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAmlPyTorchJobs) UpdateStatus(amlPyTorchJob *pytorchv1.AmlPyTorchJob) (*pytorchv1.AmlPyTorchJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(amlpytorchjobsResource, "status", c.ns, amlPyTorchJob), &pytorchv1.AmlPyTorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pytorchv1.AmlPyTorchJob), err
}

// Delete takes name of the amlPyTorchJob and deletes it. Returns an error if one occurs.
func (c *FakeAmlPyTorchJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(amlpytorchjobsResource, c.ns, name), &pytorchv1.AmlPyTorchJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAmlPyTorchJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(amlpytorchjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &pytorchv1.AmlPyTorchJobList{})
	return err
}

// Patch applies the patch and returns the patched amlPyTorchJob.
func (c *FakeAmlPyTorchJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *pytorchv1.AmlPyTorchJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(amlpytorchjobsResource, c.ns, name, pt, data, subresources...), &pytorchv1.AmlPyTorchJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*pytorchv1.AmlPyTorchJob), err
}
